# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf573e62692d4465ee0ccb89af00d6eebe17bf70d49b42b33a25dbc6d1115cfe53a21e2918d8999b29028ce3d9b3e71feb6349f68c813181feae57b469c33cfa

test:
  secret_key_base: 0654176e5aca3bf63a49ce39ff20ea761019d921b95697a745c346b784d86147d2975fcb924dad998d33efef8e349ac752da274497fd6c41d3a817f290137a28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
